package liu.mapper;

import java.util.List;
import liu.bean.Appartus;
import liu.bean.AppartusExample;
import org.apache.ibatis.annotations.Param;

public interface AppartusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int countByExample(AppartusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int deleteByExample(AppartusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int deleteByPrimaryKey(Integer appartusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int insert(Appartus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int insertSelective(Appartus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    List<Appartus> selectByExample(AppartusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    Appartus selectByPrimaryKey(Integer appartusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") Appartus record, @Param("example") AppartusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int updateByExample(@Param("record") Appartus record, @Param("example") AppartusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int updateByPrimaryKeySelective(Appartus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    int updateByPrimaryKey(Appartus record);
}