package liu.mapper;

import java.util.List;
import liu.bean.Personnel;
import liu.bean.PersonnelExample;
import org.apache.ibatis.annotations.Param;

public interface PersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int countByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int deleteByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int deleteByPrimaryKey(Integer empNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int insert(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int insertSelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    List<Personnel> selectByExample(PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    Personnel selectByPrimaryKey(Integer empNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int updateByExample(@Param("record") Personnel record, @Param("example") PersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int updateByPrimaryKeySelective(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    int updateByPrimaryKey(Personnel record);
}