package liu.bean;

import java.util.ArrayList;
import java.util.List;

public class AppartusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public AppartusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppartusIdIsNull() {
            addCriterion("APPARTUS_ID is null");
            return (Criteria) this;
        }

        public Criteria andAppartusIdIsNotNull() {
            addCriterion("APPARTUS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAppartusIdEqualTo(Integer value) {
            addCriterion("APPARTUS_ID =", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdNotEqualTo(Integer value) {
            addCriterion("APPARTUS_ID <>", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdGreaterThan(Integer value) {
            addCriterion("APPARTUS_ID >", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_ID >=", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdLessThan(Integer value) {
            addCriterion("APPARTUS_ID <", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdLessThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_ID <=", value, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdIn(List<Integer> values) {
            addCriterion("APPARTUS_ID in", values, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdNotIn(List<Integer> values) {
            addCriterion("APPARTUS_ID not in", values, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_ID between", value1, value2, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_ID not between", value1, value2, "appartusId");
            return (Criteria) this;
        }

        public Criteria andAppartusnameIsNull() {
            addCriterion("APPARTUSNAME is null");
            return (Criteria) this;
        }

        public Criteria andAppartusnameIsNotNull() {
            addCriterion("APPARTUSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andAppartusnameEqualTo(String value) {
            addCriterion("APPARTUSNAME =", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameNotEqualTo(String value) {
            addCriterion("APPARTUSNAME <>", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameGreaterThan(String value) {
            addCriterion("APPARTUSNAME >", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameGreaterThanOrEqualTo(String value) {
            addCriterion("APPARTUSNAME >=", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameLessThan(String value) {
            addCriterion("APPARTUSNAME <", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameLessThanOrEqualTo(String value) {
            addCriterion("APPARTUSNAME <=", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameLike(String value) {
            addCriterion("APPARTUSNAME like", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameNotLike(String value) {
            addCriterion("APPARTUSNAME not like", value, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameIn(List<String> values) {
            addCriterion("APPARTUSNAME in", values, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameNotIn(List<String> values) {
            addCriterion("APPARTUSNAME not in", values, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameBetween(String value1, String value2) {
            addCriterion("APPARTUSNAME between", value1, value2, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusnameNotBetween(String value1, String value2) {
            addCriterion("APPARTUSNAME not between", value1, value2, "appartusname");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceIsNull() {
            addCriterion("APPARTUS_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceIsNotNull() {
            addCriterion("APPARTUS_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceEqualTo(Integer value) {
            addCriterion("APPARTUS_PRICE =", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceNotEqualTo(Integer value) {
            addCriterion("APPARTUS_PRICE <>", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceGreaterThan(Integer value) {
            addCriterion("APPARTUS_PRICE >", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_PRICE >=", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceLessThan(Integer value) {
            addCriterion("APPARTUS_PRICE <", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceLessThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_PRICE <=", value, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceIn(List<Integer> values) {
            addCriterion("APPARTUS_PRICE in", values, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceNotIn(List<Integer> values) {
            addCriterion("APPARTUS_PRICE not in", values, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_PRICE between", value1, value2, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_PRICE not between", value1, value2, "appartusPrice");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityIsNull() {
            addCriterion("APPARTUS_QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityIsNotNull() {
            addCriterion("APPARTUS_QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityEqualTo(Integer value) {
            addCriterion("APPARTUS_QUANTITY =", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityNotEqualTo(Integer value) {
            addCriterion("APPARTUS_QUANTITY <>", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityGreaterThan(Integer value) {
            addCriterion("APPARTUS_QUANTITY >", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_QUANTITY >=", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityLessThan(Integer value) {
            addCriterion("APPARTUS_QUANTITY <", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("APPARTUS_QUANTITY <=", value, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityIn(List<Integer> values) {
            addCriterion("APPARTUS_QUANTITY in", values, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityNotIn(List<Integer> values) {
            addCriterion("APPARTUS_QUANTITY not in", values, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_QUANTITY between", value1, value2, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("APPARTUS_QUANTITY not between", value1, value2, "appartusQuantity");
            return (Criteria) this;
        }

        public Criteria andAppartusRemIsNull() {
            addCriterion("APPARTUS_REM is null");
            return (Criteria) this;
        }

        public Criteria andAppartusRemIsNotNull() {
            addCriterion("APPARTUS_REM is not null");
            return (Criteria) this;
        }

        public Criteria andAppartusRemEqualTo(String value) {
            addCriterion("APPARTUS_REM =", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemNotEqualTo(String value) {
            addCriterion("APPARTUS_REM <>", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemGreaterThan(String value) {
            addCriterion("APPARTUS_REM >", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemGreaterThanOrEqualTo(String value) {
            addCriterion("APPARTUS_REM >=", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemLessThan(String value) {
            addCriterion("APPARTUS_REM <", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemLessThanOrEqualTo(String value) {
            addCriterion("APPARTUS_REM <=", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemLike(String value) {
            addCriterion("APPARTUS_REM like", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemNotLike(String value) {
            addCriterion("APPARTUS_REM not like", value, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemIn(List<String> values) {
            addCriterion("APPARTUS_REM in", values, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemNotIn(List<String> values) {
            addCriterion("APPARTUS_REM not in", values, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemBetween(String value1, String value2) {
            addCriterion("APPARTUS_REM between", value1, value2, "appartusRem");
            return (Criteria) this;
        }

        public Criteria andAppartusRemNotBetween(String value1, String value2) {
            addCriterion("APPARTUS_REM not between", value1, value2, "appartusRem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appartus
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 29 21:08:20 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table appartus
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}