package liu.bean;

public class Appartus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appartus.APPARTUS_ID
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    private Integer appartusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appartus.APPARTUSNAME
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    private String appartusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appartus.APPARTUS_PRICE
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    private Integer appartusPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appartus.APPARTUS_QUANTITY
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    private Integer appartusQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appartus.APPARTUS_REM
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    private String appartusRem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appartus.APPARTUS_ID
     *
     * @return the value of appartus.APPARTUS_ID
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public Integer getAppartusId() {
        return appartusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appartus.APPARTUS_ID
     *
     * @param appartusId the value for appartus.APPARTUS_ID
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setAppartusId(Integer appartusId) {
        this.appartusId = appartusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appartus.APPARTUSNAME
     *
     * @return the value of appartus.APPARTUSNAME
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public String getAppartusname() {
        return appartusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appartus.APPARTUSNAME
     *
     * @param appartusname the value for appartus.APPARTUSNAME
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setAppartusname(String appartusname) {
        this.appartusname = appartusname == null ? null : appartusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appartus.APPARTUS_PRICE
     *
     * @return the value of appartus.APPARTUS_PRICE
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public Integer getAppartusPrice() {
        return appartusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appartus.APPARTUS_PRICE
     *
     * @param appartusPrice the value for appartus.APPARTUS_PRICE
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setAppartusPrice(Integer appartusPrice) {
        this.appartusPrice = appartusPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appartus.APPARTUS_QUANTITY
     *
     * @return the value of appartus.APPARTUS_QUANTITY
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public Integer getAppartusQuantity() {
        return appartusQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appartus.APPARTUS_QUANTITY
     *
     * @param appartusQuantity the value for appartus.APPARTUS_QUANTITY
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setAppartusQuantity(Integer appartusQuantity) {
        this.appartusQuantity = appartusQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appartus.APPARTUS_REM
     *
     * @return the value of appartus.APPARTUS_REM
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public String getAppartusRem() {
        return appartusRem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appartus.APPARTUS_REM
     *
     * @param appartusRem the value for appartus.APPARTUS_REM
     *
     * @mbggenerated Thu Dec 29 21:08:20 CST 2022
     */
    public void setAppartusRem(String appartusRem) {
        this.appartusRem = appartusRem == null ? null : appartusRem.trim();
    }
}