package liu.bean;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer patientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String patientGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_DATE_START
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String patientDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_DEPT
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer patientDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_STATE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String patientState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_DOC
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer patientDoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_ROOM
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer patientRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.PATIENT_BE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer patientBe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_NO
     *
     * @return the value of patient.PATIENT_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getPatientNo() {
        return patientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_NO
     *
     * @param patientNo the value for patient.PATIENT_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientNo(Integer patientNo) {
        this.patientNo = patientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_NAME
     *
     * @return the value of patient.PATIENT_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_NAME
     *
     * @param patientName the value for patient.PATIENT_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_GENDER
     *
     * @return the value of patient.PATIENT_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getPatientGender() {
        return patientGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_GENDER
     *
     * @param patientGender the value for patient.PATIENT_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientGender(String patientGender) {
        this.patientGender = patientGender == null ? null : patientGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_DATE_START
     *
     * @return the value of patient.PATIENT_DATE_START
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getPatientDateStart() {
        return patientDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_DATE_START
     *
     * @param patientDateStart the value for patient.PATIENT_DATE_START
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientDateStart(String patientDateStart) {
        this.patientDateStart = patientDateStart == null ? null : patientDateStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_DEPT
     *
     * @return the value of patient.PATIENT_DEPT
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getPatientDept() {
        return patientDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_DEPT
     *
     * @param patientDept the value for patient.PATIENT_DEPT
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientDept(Integer patientDept) {
        this.patientDept = patientDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_STATE
     *
     * @return the value of patient.PATIENT_STATE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getPatientState() {
        return patientState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_STATE
     *
     * @param patientState the value for patient.PATIENT_STATE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientState(String patientState) {
        this.patientState = patientState == null ? null : patientState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_DOC
     *
     * @return the value of patient.PATIENT_DOC
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getPatientDoc() {
        return patientDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_DOC
     *
     * @param patientDoc the value for patient.PATIENT_DOC
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientDoc(Integer patientDoc) {
        this.patientDoc = patientDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_ROOM
     *
     * @return the value of patient.PATIENT_ROOM
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getPatientRoom() {
        return patientRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_ROOM
     *
     * @param patientRoom the value for patient.PATIENT_ROOM
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientRoom(Integer patientRoom) {
        this.patientRoom = patientRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.PATIENT_BE
     *
     * @return the value of patient.PATIENT_BE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getPatientBe() {
        return patientBe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.PATIENT_BE
     *
     * @param patientBe the value for patient.PATIENT_BE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setPatientBe(Integer patientBe) {
        this.patientBe = patientBe;
    }
}