package liu.bean;

import java.util.ArrayList;
import java.util.List;

public class PersonnelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public PersonnelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmpNoIsNull() {
            addCriterion("EMP_NO is null");
            return (Criteria) this;
        }

        public Criteria andEmpNoIsNotNull() {
            addCriterion("EMP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNoEqualTo(Integer value) {
            addCriterion("EMP_NO =", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotEqualTo(Integer value) {
            addCriterion("EMP_NO <>", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoGreaterThan(Integer value) {
            addCriterion("EMP_NO >", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_NO >=", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoLessThan(Integer value) {
            addCriterion("EMP_NO <", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_NO <=", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoIn(List<Integer> values) {
            addCriterion("EMP_NO in", values, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotIn(List<Integer> values) {
            addCriterion("EMP_NO not in", values, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoBetween(Integer value1, Integer value2) {
            addCriterion("EMP_NO between", value1, value2, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_NO not between", value1, value2, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("EMP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("EMP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("EMP_NAME =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("EMP_NAME <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("EMP_NAME >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_NAME >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("EMP_NAME <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("EMP_NAME <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("EMP_NAME like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("EMP_NAME not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("EMP_NAME in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("EMP_NAME not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("EMP_NAME between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("EMP_NAME not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdIsNull() {
            addCriterion("EMP_DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdIsNotNull() {
            addCriterion("EMP_DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdEqualTo(Integer value) {
            addCriterion("EMP_DEPT_ID =", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdNotEqualTo(Integer value) {
            addCriterion("EMP_DEPT_ID <>", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdGreaterThan(Integer value) {
            addCriterion("EMP_DEPT_ID >", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_DEPT_ID >=", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdLessThan(Integer value) {
            addCriterion("EMP_DEPT_ID <", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_DEPT_ID <=", value, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdIn(List<Integer> values) {
            addCriterion("EMP_DEPT_ID in", values, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdNotIn(List<Integer> values) {
            addCriterion("EMP_DEPT_ID not in", values, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("EMP_DEPT_ID between", value1, value2, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_DEPT_ID not between", value1, value2, "empDeptId");
            return (Criteria) this;
        }

        public Criteria andEmpDutyIsNull() {
            addCriterion("EMP_DUTY is null");
            return (Criteria) this;
        }

        public Criteria andEmpDutyIsNotNull() {
            addCriterion("EMP_DUTY is not null");
            return (Criteria) this;
        }

        public Criteria andEmpDutyEqualTo(String value) {
            addCriterion("EMP_DUTY =", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyNotEqualTo(String value) {
            addCriterion("EMP_DUTY <>", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyGreaterThan(String value) {
            addCriterion("EMP_DUTY >", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_DUTY >=", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyLessThan(String value) {
            addCriterion("EMP_DUTY <", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyLessThanOrEqualTo(String value) {
            addCriterion("EMP_DUTY <=", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyLike(String value) {
            addCriterion("EMP_DUTY like", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyNotLike(String value) {
            addCriterion("EMP_DUTY not like", value, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyIn(List<String> values) {
            addCriterion("EMP_DUTY in", values, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyNotIn(List<String> values) {
            addCriterion("EMP_DUTY not in", values, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyBetween(String value1, String value2) {
            addCriterion("EMP_DUTY between", value1, value2, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpDutyNotBetween(String value1, String value2) {
            addCriterion("EMP_DUTY not between", value1, value2, "empDuty");
            return (Criteria) this;
        }

        public Criteria andEmpXlIsNull() {
            addCriterion("EMP_XL is null");
            return (Criteria) this;
        }

        public Criteria andEmpXlIsNotNull() {
            addCriterion("EMP_XL is not null");
            return (Criteria) this;
        }

        public Criteria andEmpXlEqualTo(Integer value) {
            addCriterion("EMP_XL =", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlNotEqualTo(Integer value) {
            addCriterion("EMP_XL <>", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlGreaterThan(Integer value) {
            addCriterion("EMP_XL >", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_XL >=", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlLessThan(Integer value) {
            addCriterion("EMP_XL <", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_XL <=", value, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlIn(List<Integer> values) {
            addCriterion("EMP_XL in", values, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlNotIn(List<Integer> values) {
            addCriterion("EMP_XL not in", values, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlBetween(Integer value1, Integer value2) {
            addCriterion("EMP_XL between", value1, value2, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpXlNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_XL not between", value1, value2, "empXl");
            return (Criteria) this;
        }

        public Criteria andEmpGenderIsNull() {
            addCriterion("EMP_GENDER is null");
            return (Criteria) this;
        }

        public Criteria andEmpGenderIsNotNull() {
            addCriterion("EMP_GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andEmpGenderEqualTo(String value) {
            addCriterion("EMP_GENDER =", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderNotEqualTo(String value) {
            addCriterion("EMP_GENDER <>", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderGreaterThan(String value) {
            addCriterion("EMP_GENDER >", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_GENDER >=", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderLessThan(String value) {
            addCriterion("EMP_GENDER <", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderLessThanOrEqualTo(String value) {
            addCriterion("EMP_GENDER <=", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderLike(String value) {
            addCriterion("EMP_GENDER like", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderNotLike(String value) {
            addCriterion("EMP_GENDER not like", value, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderIn(List<String> values) {
            addCriterion("EMP_GENDER in", values, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderNotIn(List<String> values) {
            addCriterion("EMP_GENDER not in", values, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderBetween(String value1, String value2) {
            addCriterion("EMP_GENDER between", value1, value2, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpGenderNotBetween(String value1, String value2) {
            addCriterion("EMP_GENDER not between", value1, value2, "empGender");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIsNull() {
            addCriterion("EMP_BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIsNotNull() {
            addCriterion("EMP_BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayEqualTo(String value) {
            addCriterion("EMP_BIRTHDAY =", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotEqualTo(String value) {
            addCriterion("EMP_BIRTHDAY <>", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayGreaterThan(String value) {
            addCriterion("EMP_BIRTHDAY >", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_BIRTHDAY >=", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayLessThan(String value) {
            addCriterion("EMP_BIRTHDAY <", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayLessThanOrEqualTo(String value) {
            addCriterion("EMP_BIRTHDAY <=", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayLike(String value) {
            addCriterion("EMP_BIRTHDAY like", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotLike(String value) {
            addCriterion("EMP_BIRTHDAY not like", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIn(List<String> values) {
            addCriterion("EMP_BIRTHDAY in", values, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotIn(List<String> values) {
            addCriterion("EMP_BIRTHDAY not in", values, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayBetween(String value1, String value2) {
            addCriterion("EMP_BIRTHDAY between", value1, value2, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotBetween(String value1, String value2) {
            addCriterion("EMP_BIRTHDAY not between", value1, value2, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpHometownIsNull() {
            addCriterion("EMP_HOMETOWN is null");
            return (Criteria) this;
        }

        public Criteria andEmpHometownIsNotNull() {
            addCriterion("EMP_HOMETOWN is not null");
            return (Criteria) this;
        }

        public Criteria andEmpHometownEqualTo(String value) {
            addCriterion("EMP_HOMETOWN =", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownNotEqualTo(String value) {
            addCriterion("EMP_HOMETOWN <>", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownGreaterThan(String value) {
            addCriterion("EMP_HOMETOWN >", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_HOMETOWN >=", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownLessThan(String value) {
            addCriterion("EMP_HOMETOWN <", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownLessThanOrEqualTo(String value) {
            addCriterion("EMP_HOMETOWN <=", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownLike(String value) {
            addCriterion("EMP_HOMETOWN like", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownNotLike(String value) {
            addCriterion("EMP_HOMETOWN not like", value, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownIn(List<String> values) {
            addCriterion("EMP_HOMETOWN in", values, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownNotIn(List<String> values) {
            addCriterion("EMP_HOMETOWN not in", values, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownBetween(String value1, String value2) {
            addCriterion("EMP_HOMETOWN between", value1, value2, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpHometownNotBetween(String value1, String value2) {
            addCriterion("EMP_HOMETOWN not between", value1, value2, "empHometown");
            return (Criteria) this;
        }

        public Criteria andEmpCountryIsNull() {
            addCriterion("EMP_COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andEmpCountryIsNotNull() {
            addCriterion("EMP_COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andEmpCountryEqualTo(String value) {
            addCriterion("EMP_COUNTRY =", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryNotEqualTo(String value) {
            addCriterion("EMP_COUNTRY <>", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryGreaterThan(String value) {
            addCriterion("EMP_COUNTRY >", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_COUNTRY >=", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryLessThan(String value) {
            addCriterion("EMP_COUNTRY <", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryLessThanOrEqualTo(String value) {
            addCriterion("EMP_COUNTRY <=", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryLike(String value) {
            addCriterion("EMP_COUNTRY like", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryNotLike(String value) {
            addCriterion("EMP_COUNTRY not like", value, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryIn(List<String> values) {
            addCriterion("EMP_COUNTRY in", values, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryNotIn(List<String> values) {
            addCriterion("EMP_COUNTRY not in", values, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryBetween(String value1, String value2) {
            addCriterion("EMP_COUNTRY between", value1, value2, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpCountryNotBetween(String value1, String value2) {
            addCriterion("EMP_COUNTRY not between", value1, value2, "empCountry");
            return (Criteria) this;
        }

        public Criteria andEmpNationIsNull() {
            addCriterion("EMP_NATION is null");
            return (Criteria) this;
        }

        public Criteria andEmpNationIsNotNull() {
            addCriterion("EMP_NATION is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNationEqualTo(String value) {
            addCriterion("EMP_NATION =", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationNotEqualTo(String value) {
            addCriterion("EMP_NATION <>", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationGreaterThan(String value) {
            addCriterion("EMP_NATION >", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_NATION >=", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationLessThan(String value) {
            addCriterion("EMP_NATION <", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationLessThanOrEqualTo(String value) {
            addCriterion("EMP_NATION <=", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationLike(String value) {
            addCriterion("EMP_NATION like", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationNotLike(String value) {
            addCriterion("EMP_NATION not like", value, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationIn(List<String> values) {
            addCriterion("EMP_NATION in", values, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationNotIn(List<String> values) {
            addCriterion("EMP_NATION not in", values, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationBetween(String value1, String value2) {
            addCriterion("EMP_NATION between", value1, value2, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpNationNotBetween(String value1, String value2) {
            addCriterion("EMP_NATION not between", value1, value2, "empNation");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("EMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("EMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(String value) {
            addCriterion("EMP_ID =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(String value) {
            addCriterion("EMP_ID <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(String value) {
            addCriterion("EMP_ID >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_ID >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(String value) {
            addCriterion("EMP_ID <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(String value) {
            addCriterion("EMP_ID <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLike(String value) {
            addCriterion("EMP_ID like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotLike(String value) {
            addCriterion("EMP_ID not like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<String> values) {
            addCriterion("EMP_ID in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<String> values) {
            addCriterion("EMP_ID not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(String value1, String value2) {
            addCriterion("EMP_ID between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(String value1, String value2) {
            addCriterion("EMP_ID not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageIsNull() {
            addCriterion("EMP_MARRIAGE is null");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageIsNotNull() {
            addCriterion("EMP_MARRIAGE is not null");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageEqualTo(Integer value) {
            addCriterion("EMP_MARRIAGE =", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageNotEqualTo(Integer value) {
            addCriterion("EMP_MARRIAGE <>", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageGreaterThan(Integer value) {
            addCriterion("EMP_MARRIAGE >", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_MARRIAGE >=", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageLessThan(Integer value) {
            addCriterion("EMP_MARRIAGE <", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_MARRIAGE <=", value, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageIn(List<Integer> values) {
            addCriterion("EMP_MARRIAGE in", values, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageNotIn(List<Integer> values) {
            addCriterion("EMP_MARRIAGE not in", values, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageBetween(Integer value1, Integer value2) {
            addCriterion("EMP_MARRIAGE between", value1, value2, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpMarriageNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_MARRIAGE not between", value1, value2, "empMarriage");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoIsNull() {
            addCriterion("EMP_TELENO is null");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoIsNotNull() {
            addCriterion("EMP_TELENO is not null");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoEqualTo(String value) {
            addCriterion("EMP_TELENO =", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoNotEqualTo(String value) {
            addCriterion("EMP_TELENO <>", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoGreaterThan(String value) {
            addCriterion("EMP_TELENO >", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_TELENO >=", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoLessThan(String value) {
            addCriterion("EMP_TELENO <", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoLessThanOrEqualTo(String value) {
            addCriterion("EMP_TELENO <=", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoLike(String value) {
            addCriterion("EMP_TELENO like", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoNotLike(String value) {
            addCriterion("EMP_TELENO not like", value, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoIn(List<String> values) {
            addCriterion("EMP_TELENO in", values, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoNotIn(List<String> values) {
            addCriterion("EMP_TELENO not in", values, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoBetween(String value1, String value2) {
            addCriterion("EMP_TELENO between", value1, value2, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpTelenoNotBetween(String value1, String value2) {
            addCriterion("EMP_TELENO not between", value1, value2, "empTeleno");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNull() {
            addCriterion("EMP_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNotNull() {
            addCriterion("EMP_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailEqualTo(String value) {
            addCriterion("EMP_EMAIL =", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotEqualTo(String value) {
            addCriterion("EMP_EMAIL <>", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThan(String value) {
            addCriterion("EMP_EMAIL >", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_EMAIL >=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThan(String value) {
            addCriterion("EMP_EMAIL <", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThanOrEqualTo(String value) {
            addCriterion("EMP_EMAIL <=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLike(String value) {
            addCriterion("EMP_EMAIL like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotLike(String value) {
            addCriterion("EMP_EMAIL not like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIn(List<String> values) {
            addCriterion("EMP_EMAIL in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotIn(List<String> values) {
            addCriterion("EMP_EMAIL not in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailBetween(String value1, String value2) {
            addCriterion("EMP_EMAIL between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotBetween(String value1, String value2) {
            addCriterion("EMP_EMAIL not between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdIsNull() {
            addCriterion("EMP_JOB_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdIsNotNull() {
            addCriterion("EMP_JOB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdEqualTo(Integer value) {
            addCriterion("EMP_JOB_ID =", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdNotEqualTo(Integer value) {
            addCriterion("EMP_JOB_ID <>", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdGreaterThan(Integer value) {
            addCriterion("EMP_JOB_ID >", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_JOB_ID >=", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdLessThan(Integer value) {
            addCriterion("EMP_JOB_ID <", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_JOB_ID <=", value, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdIn(List<Integer> values) {
            addCriterion("EMP_JOB_ID in", values, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdNotIn(List<Integer> values) {
            addCriterion("EMP_JOB_ID not in", values, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdBetween(Integer value1, Integer value2) {
            addCriterion("EMP_JOB_ID between", value1, value2, "empJobId");
            return (Criteria) this;
        }

        public Criteria andEmpJobIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_JOB_ID not between", value1, value2, "empJobId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personnel
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 29 21:08:19 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personnel
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}