package liu.bean;

public class Personnel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_DEPT_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer empDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_DUTY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_XL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer empXl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_BIRTHDAY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_HOMETOWN
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empHometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_COUNTRY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_NATION
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_MARRIAGE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer empMarriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_TELENO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empTeleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_EMAIL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private String empEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel.EMP_JOB_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    private Integer empJobId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_NO
     *
     * @return the value of personnel.EMP_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_NO
     *
     * @param empNo the value for personnel.EMP_NO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_NAME
     *
     * @return the value of personnel.EMP_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_NAME
     *
     * @param empName the value for personnel.EMP_NAME
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_DEPT_ID
     *
     * @return the value of personnel.EMP_DEPT_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getEmpDeptId() {
        return empDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_DEPT_ID
     *
     * @param empDeptId the value for personnel.EMP_DEPT_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpDeptId(Integer empDeptId) {
        this.empDeptId = empDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_DUTY
     *
     * @return the value of personnel.EMP_DUTY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpDuty() {
        return empDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_DUTY
     *
     * @param empDuty the value for personnel.EMP_DUTY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpDuty(String empDuty) {
        this.empDuty = empDuty == null ? null : empDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_XL
     *
     * @return the value of personnel.EMP_XL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getEmpXl() {
        return empXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_XL
     *
     * @param empXl the value for personnel.EMP_XL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpXl(Integer empXl) {
        this.empXl = empXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_GENDER
     *
     * @return the value of personnel.EMP_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_GENDER
     *
     * @param empGender the value for personnel.EMP_GENDER
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_BIRTHDAY
     *
     * @return the value of personnel.EMP_BIRTHDAY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpBirthday() {
        return empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_BIRTHDAY
     *
     * @param empBirthday the value for personnel.EMP_BIRTHDAY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpBirthday(String empBirthday) {
        this.empBirthday = empBirthday == null ? null : empBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_HOMETOWN
     *
     * @return the value of personnel.EMP_HOMETOWN
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpHometown() {
        return empHometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_HOMETOWN
     *
     * @param empHometown the value for personnel.EMP_HOMETOWN
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpHometown(String empHometown) {
        this.empHometown = empHometown == null ? null : empHometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_COUNTRY
     *
     * @return the value of personnel.EMP_COUNTRY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpCountry() {
        return empCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_COUNTRY
     *
     * @param empCountry the value for personnel.EMP_COUNTRY
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpCountry(String empCountry) {
        this.empCountry = empCountry == null ? null : empCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_NATION
     *
     * @return the value of personnel.EMP_NATION
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpNation() {
        return empNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_NATION
     *
     * @param empNation the value for personnel.EMP_NATION
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpNation(String empNation) {
        this.empNation = empNation == null ? null : empNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_ID
     *
     * @return the value of personnel.EMP_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_ID
     *
     * @param empId the value for personnel.EMP_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_MARRIAGE
     *
     * @return the value of personnel.EMP_MARRIAGE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getEmpMarriage() {
        return empMarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_MARRIAGE
     *
     * @param empMarriage the value for personnel.EMP_MARRIAGE
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpMarriage(Integer empMarriage) {
        this.empMarriage = empMarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_TELENO
     *
     * @return the value of personnel.EMP_TELENO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpTeleno() {
        return empTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_TELENO
     *
     * @param empTeleno the value for personnel.EMP_TELENO
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpTeleno(String empTeleno) {
        this.empTeleno = empTeleno == null ? null : empTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_EMAIL
     *
     * @return the value of personnel.EMP_EMAIL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_EMAIL
     *
     * @param empEmail the value for personnel.EMP_EMAIL
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel.EMP_JOB_ID
     *
     * @return the value of personnel.EMP_JOB_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public Integer getEmpJobId() {
        return empJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel.EMP_JOB_ID
     *
     * @param empJobId the value for personnel.EMP_JOB_ID
     *
     * @mbggenerated Thu Dec 29 21:08:19 CST 2022
     */
    public void setEmpJobId(Integer empJobId) {
        this.empJobId = empJobId;
    }
}