spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    username: root
    password: 711018
    url: jdbc:mysql://localhost:3306/lls
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

